name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Databricks Deploy
        uses: antstackio/databricks-deploy@v1.0.4
        with:
          # Hostname of the Databricks workspace
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          # Repo Id of the Databricks repo
          #databricks-repo-id: ${{ secrets.DATABRICKS_REPO_ID }}
          # The branch of the Databricks repo to update
          #databricks-repo-branch: main  # Change this to your branch
          # Databricks token
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          notebooks-path: '/Users/yash.tiwari@celebaltech.com/Testone'
