name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2'

      - name: Import Notebooks to Databricks
        uses: microsoft/databricks-import-directory@v1.0.0
        with:
           databricks-host: ${{ secrets.DATABRICKS_HOST }}
           databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
           local-path: ./notebooks/Users/yash.tiwari@celebaltech.com
           remote-path: /Users/yash.tiwari@celebaltech.com/Testone
